FROM node:20-alpine as build

WORKDIR /app

ADD package.json /app/package.json

RUN npm i -g pnpm
RUN apk update && apk add --no-cache git
RUN pnpm install -P

ADD . /app

RUN pnpm run build:chatbot

CMD ["pnpm", "run" ,"run:chatbot"]