FROM node:20-alpine

RUN apt-get update \
    && apt-get install -y \
    git 

WORKDIR /app
ADD package.json /app/package.json

RUN npm i -g pnpm

RUN pnpm install

ADD . /app

RUN npm run back:build

CMD ["npm", "run", "back:run"]