FROM node:20-alpine as build

WORKDIR /app

ADD package.json /app/package.json

RUN npm i -g pnpm
RUN apk update
RUN apk add --no-cache \
      chromium \
      nss \
      freetype \
      harfbuzz \
      ca-certificates \
      ttf-freefont \
      nodejs \
      yarn \
      git

RUN pnpm install

ADD . /app

RUN npm run back:build

CMD ["npm", "run", "back:run"]